Docker/doxygen
Teaching-projects/SZE-MoSzE-2019-DreamTheater pull request #11
Opened 2019-12-05 09:35 UTC by Comerick

2019-12-07 23:27 UTC, hegyhati requested changes
az image-et midnenkepp szedjketek szet 1-2 kisebbre, mintsem hogy 1 nagy legyen, illetve a doxtyfile-os dolgot tegyetek rendbe.

2019-12-07 23:27 UTC, hegyhati commented on .circleci/config.yml
> +              doxygen -g Doxyfile
nem, a Doxyfile-t azt ne a CI-ban generaljatok, hanem legyen a repo resze.

2019-12-07 23:27 UTC, hegyhati commented on .circleci/config.yml
> +              doxygen -g Doxyfile
illetve hol a deploy?

2019-12-07 23:27 UTC, hegyhati commented on .circleci/images/Dockerfile
> +  && rm -rf /googletest
most akkor ez a PR mirol szol? dockerol vagy doxygen-rol? 1 PR 1 feature, elmondtuk eleg sokszor. 

A masik dolog, hogy ne 1 docker image-et csinaljatok, amibe mindent beleraktok. Felesleges a doxygennek meg a google test-nek pl egy image-ben lennie.

2019-12-08 11:41 UTC, Comerick commented
Mivel gh-pages branch erősen erre a branchre épül, ezért inkább ezt le is zárnám.

2019-12-08 11:41 UTC, closed without merging