Docs deploy
Teaching-projects/SZE-MoSzE-2019-DreamTheater pull request #12
Opened 2019-12-06 05:04 UTC by Comerick

2019-12-07 23:36 UTC, hegyhati requested changes
Az 1 PR 1 feature dolgot megint nem sikerult tartani, de alapvetoen szep, meg orulok, hogy megy a gh-pages deploy. De a doxyfile generalast tessek kivenni, meg nem egy giga docker image-et csinalni, amiben minden benne van, hanem logikusan szetszedni mi az, ami a buildeleshez, mi az, ami a teszteleshez, dokumentacio generalashoz kell.

2019-12-07 23:36 UTC, hegyhati commented on .circleci/config.yml
> +              doxygen -g Doxyfile
a doxyfile-t ne on the fly generaljatok, az legyen a repo resze.

2019-12-07 23:36 UTC, hegyhati commented on .circleci/images/Dockerfile
> +WORKDIR /googletest/build
ne egy image-ben legyen minden, szedjetek szet.

2019-12-08 11:36 UTC, Comerick commented
Szétszedtem nagyjából ahogy logikusnak láttam az imageket.
Kettő még nincs használatban, azokat később fogom hasznlatba venni
Remélem a doxyfile már így jó lesz.
Működni működni fog, de a doxygen nem fogja behuzni a src fileokat, egy üres doksit le fog tudni generálni, ha mergelve lesz
Abban esetleg segítséget kérnék, hogy a doxyfileba melyik option a lúdas a dologba.

2019-12-09 15:45 UTC, hegyhati commented on .circleci/images/Dockerfile
> +RUN npm install -g --silent gh-pages@2.0.1
Ezek miert vannak egy file-ban?! hogy keszited el ebbol atobbi image-et?

2019-12-09 15:47 UTC, hegyhati commented
> Remélem a doxyfile már így jó lesz.
> Működni működni fog, de a doxygen nem fogja behuzni a src fileokat, egy üres doksit le fog tudni generálni, ha mergelve lesz
> Abban esetleg segítséget kérnék, hogy a doxyfileba melyik option a lúdas a dologba.

Most egyaltalan azt sem ertem, hogy minek van itt a doxy-s dolog, ha meg nincsenek doxygen kommentek. De vegulis elfer. A problemadat viszont nem ertem.

2019-12-23 21:27 UTC, Comerick commented
Végül egy pdf-es doksit csináltam, amit eltárolok egy artifactként.
A html-es megoldást hanyagoltam az ssh kulcsokkal való gondok miatt.

2020-01-02 17:06 UTC, hegyhati approved these changes

2020-01-02 17:07 UTC, merged