@hegyhati A lemaradt remove command kész
Teaching-projects/SZE-MoSzE-2019-DreamTheater pull request #3
Opened 2019-11-07 20:32 UTC by Comerick

2019-11-08 14:21 UTC, hegyhati requested changes
Van mit rendbetenni, lasd kommentek.

2019-11-08 14:21 UTC, hegyhati commented on Directory.cpp
> +    for(auto i:this->getFile()){
ez inkabb getFiles kellene legyen, nem?

2019-11-08 14:21 UTC, hegyhati commented on Directory.cpp
> +    cout<< searchedDir->getName()<< endl;
es ha nullptr?

2019-11-08 14:21 UTC, hegyhati commented on Directory.cpp
> +return files.push_back(new File(s));
void es return?!

2019-11-08 14:21 UTC, hegyhati commented on Directory.cpp
>  return subFolder.push_back(new Directory(s,this));
u.a.. llefordul ez egyaltalan?!

2019-11-08 14:21 UTC, hegyhati commented on Directory.cpp
> +    if(getSubFolder().empty()){
itt miert nem ered el direktben az adattagot, miert fuggvenyen keresztul? illetve if (feltetel) return true, else return false? Na, azert ezt lehetne 1 sorban is szebben ;-)

2019-11-08 14:21 UTC, hegyhati commented on Directory.cpp
> +    return false;
u.a.

2019-11-08 14:21 UTC, hegyhati commented on Filesystem.cpp
> +for(auto& i : Directorys){
nezzetek meg a directory tobbesszamat ;-)

2019-11-08 14:21 UTC, hegyhati commented on Filesystem.cpp
> +    }
Ezt minek teszteled kulon?

2019-11-08 14:21 UTC, hegyhati commented on Filesystem.cpp
> +        if(i->getName()==args.front()){
talanm jobban megerne, ha lenne egy `Directory::has(string)`. akkor nem kellene itt mindenen vegigmenni. Illetve azt nem teszteled le, hogy olyan nevu konyvtar mar van-e, akkor sem lehet file-t letrehozni azzal a nevvel.

2019-11-08 14:21 UTC, hegyhati commented on Filesystem.cpp
> +    currentDir->remove(args.front());
u.a.

2019-11-09 05:55 UTC, Comerick commented on Filesystem.cpp
> +    }
Frissebb fejjel már máshogyan fest a dolog..:D

2019-11-11 15:43 UTC, hegyhati approved these changes

2019-11-11 15:43 UTC, hegyhati commented on Filesystem.cpp
>      }
namost pepitaban ugyanennek a logikanak meg kellene lennie pl az mkdir-ben is, nem? (de ott mas van). Ha pedig mar ket helyen meg kellene lennie....

2019-11-11 15:45 UTC, merged