Load file feature
Teaching-projects/SZE-MoSzE-2019-DreamTheater pull request #8
Opened 2019-11-26 19:06 UTC by Comerick

2019-12-04 16:00 UTC, wajzy requested changes
A memóriaszivárgást és a szegmentációs hibát el kellene távolítani, utána részemről mehet a merge.

2019-12-04 16:00 UTC, wajzy commented on Filesystem.cpp
> +                    cout << "Need more argument to use this command! Echo sytanx: echo <content> <destination>"<<endl;
A feladatkiírás nem egészen így nézett ki (volt benne egy > ), de ám legyen.

2019-12-04 16:00 UTC, wajzy commented on Directory.cpp
> +Directory* Directory::searchDir(string s){
Nem tudom, ezt a const-ot miért kellett eltávolítani.

2019-12-04 16:00 UTC, wajzy commented on Filesystem.cpp
> +            currentDir->echo(content, filename);
És mi van akkor, ha nem valid a fájlnév, emiatt új fájl sem jön létre, majd abba bele akarunk tenni valamilyen tartalmat?

2019-12-04 16:00 UTC, wajzy commented on Directory.cpp
> +    file->setContent(content);
Ez is elég aggasztó. Ha searchFile visszaad egy nullptr-t, simán maghívjuk majd a tagfüggvényét? Elvileg ilyen nem fog előfordulni, mert a FileSystem::echo ezt előzőleg ellenőrzi, de akkor is...

2019-12-04 16:00 UTC, wajzy commented on Directory.cpp
> -        delete s;
Nem tudom, ez okozza-e, de egy
mkdir egy
rm egy
quit
után ezt kaptam:
==32404== LEAK SUMMARY:
==32404==    definitely lost: 88 bytes in 1 blocks

2019-12-05 05:24 UTC, Comerick commented on Filesystem.cpp
> +            currentDir->echo(content, filename);
Javítom is

2019-12-05 05:33 UTC, Comerick commented on Directory.cpp
> -        delete s;
Igen valószínűleg az, kijavítottam már régebben `subFolders.remove(s);`-re. Az újabb verziókba, vagy másik branchbe benne kell lennie a javításnak

2019-12-05 05:49 UTC, Comerick commented on Directory.cpp
> +    file->setContent(content);
Megtudnám még úgy csinálni, hogy a makefile függvény visszaad egy file pointert, utána meg azzal dolgozok és nem kell állandóan megkeresgetni.

2019-12-06 16:08 UTC, wajzy approved these changes

2019-12-06 16:08 UTC, wajzy commented on Directory.cpp
> +    file->setContent(content);
OK

2019-12-06 16:09 UTC, wajzy approved these changes

2019-12-07 22:28 UTC, hegyhati commented
@Comerick, oldjatok fel a conflicteket, aztan @wajzy meg egyet rapillant, es ha bolint, akkor mehet be.

2019-12-08 11:38 UTC, Comerick commented
Sikerült feloldani a conflicteket.

2019-12-09 12:35 UTC, wajzy approved these changes

2019-12-09 12:35 UTC, wajzy approved these changes

2019-12-09 15:47 UTC, merged